module:
  admin_toolbar: 0
  block: 0
  breakpoint: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  datetime: 0
  datetime_range: 0
  docstore: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  entity_reference: 0
  entity_reference_uuid: 0
  entity_usage: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geofield: 0
  image: 0
  language: 0
  media: 0
  node: 0
  options: 0
  page_cache: 0
  path_alias: 0
  search_api: 0
  search_api_solr: 0
  serialization: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  user: 0
  user_bundle: 0
  webhooks: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  bartik: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
